---
apiVersion: v1
kind: Namespace
metadata:
  name: argentina
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argentina
  namespace: argentina
spec:
  selector:
    matchLabels:
      app: argentina
  replicas: 1
  template:
    metadata:
      labels:
        app: argentina
    spec:
      containers:
      - image: marcosluv/desafio-meli:test
        name: argentina
        env:
          - name: APP_NAME
            valueFrom:
              configMapKeyRef:
                name: configmap-api
                key: APP_NAME
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: configmap-api
                key: DB_PORT
          - name: DB_NOME
            valueFrom:
              configMapKeyRef:
                name: configmap-api
                key: DB_NOME
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: configmap-api
                key: DB_URL
          - name: DB_USUARIO
            valueFrom:
              configMapKeyRef:
                name: configmap-api
                key: DB_USUARIO      
          - name: API_PORT
            valueFrom:
              configMapKeyRef:
                name: configmap-api
                key: API_PORT
          - name: DB_SENHA
            valueFrom:
              secretKeyRef:
                name: secret-db-api
                key: DB_SENHA       
---
apiVersion: v1
kind: Service
metadata:
  name: argentina
  namespace: argentina
spec:
  ports:
  - targetPort: 8080 
    port: 3001
    nodePort: 30001
    protocol: TCP
  type: NodePort
  selector:
    app: argentina
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-api
  namespace: argentina
data:
  APP_NAME: "argentina"
  DB_PORT: "3306"
  DB_USUARIO: "desafio"
  DB_URL: "desafio-api.c83ipwcuxs6c.us-east-1.rds.amazonaws.com"
  DB_NOME: "argentina"
  API_PORT: "8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-db-api
  namespace: argentina
type: Opaque
data:
  DB_SENHA: TSRsYTVXTnRBNXFU 