name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./desafio_api/.
          push: true
          tags: marcosluv/desafio-meli:latest

#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Apply Manifests in EKS
#        uses: azure/k8s-set-context@v1
#        with:
#          kubeconfig: ${{ secrets.KUBECONFIG }}
#
#      - name: Apply Kubernetes manifest
#        run: kubectl apply -f ./k8s/ --recursive
